site_name: Fortran programming
repo_url: https://pranabdas.github.io/
site_description: Learning programming in Fortran 
site_author: Pranab Das

nav:
    - Table of Contents: index.md 
    - Getting started: gs.md 
    - Fortran basics: basics.md 
    - Array: array.md 
    - Logical expression and control: control.md
    - Loop: loop.md 
    - File I/O: file.md 

theme:
    name: null
    custom_dir: simplicity
    static_templates:
        - 404.html

    include_search_page: true
    search_index_only: false

    highlightjs: true

markdown_extensions:
    - pymdownx.arithmatex
    - attr_list
