[build]
  command = """
  wget https://raw.githubusercontent.com/pranabdas/espresso/refs/heads/main/scripts/build_docusaurus.sh
  sed -i 's|baseUrl:.*|baseUrl: "/",|I' docusaurus.config.js
  bash build_docusaurus.sh
  """

  publish = "build"

[build.environment]
  NODE_VERSION = "lts/*"
