module.exports = {
  docs: [
    "setup",
    "basics",
    "array",
    "control",
    "loop",
    "modules",
    "procedures",
    "complex",
    "recursion",
    "types",
    "pointer",
    "file",
    {
      type: "category",
      label: "Coding practice",
      collapsed: true,
      link: {
        type: "generated-index",
      },
      items: [
        "swap",
        "abs-path",
        "hypotenuse",
        "integration",
        "haversine",
        "inner-product",
        "monte-carlo-pi",
        "monte-carlo-integration",
        "time",
        "arg-parsing",
        "exec-command",
        "blas",
        "mpi",
      ],
    },
    "resources",
    "license",
  ],
};
