module.exports = {
  docs: [
    "setup",
    "basics",
    "array",
    "control",
    "loop",
    "modules",
    "procedures",
    "complex",
    "recursion",
    "types",
    "pointer",
    "file-io",
    {
      type: "category",
      label: "Coding practice",
      collapsed: true,
      link: {
        type: "generated-index",
      },
      items: [
        "coding-practice/swap",
        "coding-practice/abs-path",
        "coding-practice/hypotenuse",
        "coding-practice/integration",
        "coding-practice/haversine",
        "coding-practice/inner-product",
        "coding-practice/monte-carlo-pi",
        "coding-practice/monte-carlo-integration",
        "coding-practice/time",
        "coding-practice/arg-parsing",
        "coding-practice/exec-command",
        "coding-practice/blas",
        "coding-practice/mpi",
      ],
    },
    "resources",
    "license",
  ],
};
